version: "3"

services:
  rank_app:
    build: ./ranking_app
    image: rank_app
    restart: always
    ports:
      - "5001:5001"
    container_name: rank_app_con
  price_app:
    build: ./pricing_app
    image: price_app
    restart: always
    ports:
      - "5002:5002"
    container_name: price_app_con
  top_coins_app:
    build: ./topcoins_app
    image: topcoins_app
    restart: always
    ports:
      - "5000:5000"
    container_name: top_coins_app_con